name: fastfinder_build_linux

on: [push, pull_request]

jobs:
  linux_standard-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bison \
            flex \
            autoconf \
            pkg-config \
            automake \
            libtool \
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.17
      - name: Install YARA v4.1
        run: |
          YARA_VERSION=4.1.3
          wget --no-verbose -O- https://github.com/VirusTotal/yara/archive/v${YARA_VERSION}.tar.gz | tar -C /tmp -xzf -
          ( cd /tmp/yara-${YARA_VERSION} && ./bootstrap.sh && sudo ./configure && sudo make && sudo make install )
      - uses: actions/checkout@v2
      - name: Building Fastfinder
        run: |
           go build -trimpath -tags yara_static -a -ldflags '-s -w -extldflags "-static"' .
           ls
           sudo chmod +x fastfinder
           sudo ./fastfinder -h